### ISSUE TITLE
Gritty broken

### ISSUE THREAD

**Issue by olivmonnier** [cloudcmd/gritty#10]
Hi, 
xterm webgl addon seems broke gritty:
![Capture d’écran 2020-03-24 à 10 45 17](https://user-images.githubusercontent.com/2937198/77411467-c8e5bd00-6dbc-11ea-9fe1-37a4e22b1a17.png)

**Comment by coderaiser** [comment]
Hi :), thank you, looks like it's related to https://github.com/xtermjs/xterm.js/issues/2759.

**Comment by coderaiser** [comment]
Fixed with https://github.com/cloudcmd/gritty/commit/08051183a76754c5c926f197b996cd3ea1a315bf, landed in [v4.8.10](https://github.com/cloudcmd/gritty/releases/tag/v4.8.10) :tada: Is it works for you now?

**Comment by olivmonnier** [comment]
Yeah ! It seems ok :+1: :sparkles:
