### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by marcuzz0** [cloudcmd/gritty#12]
Hello to all,
when I try to install gritty with the terminal command
here is an error:

root@XXXXXXX:~# npm install gritty -g
/usr/bin/gritty -> /usr/lib/node_modules/gritty/bin/gritty.js

> node-pty@0.9.0 install /usr/lib/node_modules/gritty/node_modules/node-pty
> node scripts/install.js

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/10.23.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp'
gyp ERR! System Linux 4.19.0-12-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/gritty/node_modules/node-pty
gyp ERR! node -v v10.23.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for gritty@5.0.0: wanted: {"node":">=12"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: gritty@5.0.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-11T14_08_39_099Z-debug.log

someone can help me?
Marco

**Comment by coderaiser** [comment]
Install [nvm](https://github.com/nvm-sh/nvm) first, then install again `gritty`. 
Is it helps?

**Comment by marcuzz0** [comment]
no, always the same mistake

**Comment by coderaiser** [comment]
Try to set [prefix](https://docs.npmjs.com/cli/v6/commands/npm-prefix) to your `~/.npmrc`:

```
prefix=/home/your-user/.npm-packages
```

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
