### ISSUE TITLE
How I Use Authentication 

### ISSUE THREAD

**Issue by JohanChungus** [cloudcmd/gritty#17]
Can You Give Me The Example Code That Allow Me Use Authentication To Login. I Ask ChatGPT But ChatGPT Give Me Wrong Answer 😞

**Comment by coderaiser** [comment]
Sure, [here it is](https://github.com/cloudcmd/gritty#grittylistensocket--options):

```js
const prefix = '/gritty'; // default

const auth = (accept, reject) => (username, password) => {
    accept();
};

gritty.listen(socket, {
    prefix,
    auth, // optional
});
```

**Comment by JohanChungus** [comment]
Ok thanks
