### ISSUE TITLE
Change style

### ISSUE THREAD

**Issue by maytinhdibo** [cloudcmd/gritty#4]
How to change style of terminal?

**Comment by coderaiser** [comment]
What exactly do you want to change?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝

**Comment by maytinhdibo** [comment]
I hope can change font size or background color of terminal.

**Comment by coderaiser** [comment]
You can try to override style of [xterm.js](https://xtermjs.org/).

**Comment by subins2000** [comment]
It'd be great if there's a CLI option to change font

**Comment by coderaiser** [comment]
This is a good idea for a pull request :).
