### ISSUE TITLE
menus in terminal-kit broken starting from 4.4.0 (getCursorLocation timed out)

### ISSUE THREAD

**Issue by ulno** [cloudcmd/gritty#6]
The last version where terminal-kit shows working menus in gritty is 4.3.10.
Starting with 4.4.0 programs using in menus in terminal-kit show:
``Error: .getCursorLocation() timed out``

**Comment by coderaiser** [comment]
The problem should be somewhere [here](https://github.com/cloudcmd/gritty/commit/4c214ee1fb17d3396b412521c6fd6c4d6d043502) in this case.

**Comment by coderaiser** [comment]
Or it can be related with update of `xterm` to [v3.13.1](https://github.com/xtermjs/xterm.js/releases/tag/3.13.1), or  https://github.com/cronvel/terminal-kit/issues/74

**Comment by coderaiser** [comment]
Just [updated](https://github.com/cloudcmd/gritty/releases/tag/v4.4.2) `gritty` to [xterm v3.13.2](https://github.com/xtermjs/xterm.js/releases/tag/3.13.2), could you please check if it helps?

**Comment by ulno** [comment]
Switching to 4.4.2 solves the problem.
So, it must have been xterm v3.13.1->2?
Thanks for the quick fix!

**Comment by coderaiser** [comment]
> So, it must have been xterm v3.13.1->2?

Yes, or [v3.13.0](https://github.com/xtermjs/xterm.js/releases/tag/3.13.0). It looks like one of them :).
